apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-sample-devfile-sample-python-basic-xtu5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-rick-tenant/rhtap-sample-devfile-sample-python-basic-1/rhtap-sample-devfile-sample-python-basic-xtu5@sha256:7540fd379bf796323be708fbbca587b1dc9980a1eea1390ee213717649bc661e
        name: my-python
        resources: {}
status: {}
