apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-sample-devfile-sample-python-basic-xtu5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-sample-devfile-sample-python-basic-xtu5
    app.kubernetes.io/part-of: rhtap-sample-devfile-sample-python-basic-1
  name: rhtap-sample-devfile-sampoj7n
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: rhtap-sample-devfile-sample-python-basic-xtu5
    weight: null
status: {}
