apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-sample-devfile-sample-python-basic-xtu5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-sample-devfile-sample-python-basic-xtu5
    app.kubernetes.io/part-of: rhtap-sample-devfile-sample-python-basic-1
  name: rhtap-sample-devfile-sample-python-basic-xtu5
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: rhtap-sample-devfile-sample-python-basic-xtu5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: rhtap-sample-devfile-sample-python-basic-xtu5
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-rick-tenant/rhtap-sample-devfile-sample-python-basic-1/rhtap-sample-devfile-sample-python-basic-xtu5@sha256:7540fd379bf796323be708fbbca587b1dc9980a1eea1390ee213717649bc661e
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
